services:
  letter-storage-db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${LETTER_STORAGE_DB_NAME}
      POSTGRES_USER: ${LETTER_STORAGE_DB_USER}
      POSTGRES_PASSWORD: ${LETTER_STORAGE_DB_PASSWORD}
    networks:
      - letter-storage-net
    ports:
      - "5432:5432"
    volumes:
      - letter-storage-db-data:/var/lib/postgresql/data

  letter-storage-service:
    # image: letter-storage-service-img
    build: . # 현재 디렉토리의 Dockerfile을 사용하여 이미지를 빌드
    env_file: .env
    networks:
      - letter-storage-net
    ports:
      - "8007:8000"
    depends_on:
      - letter-storage-db

networks:
  letter-storage-net:
    external: true

volumes:
  letter-storage-db-data:
